yatube/about/urls.py
from django.urls import path
from . import views


app_name = "about"


urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name='author'),
    path("tech/", views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"


urlpatterns = [
    #Главная страница
    path("", views.index, name='index'),
    # в качестве параметра ожидает slug строку
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),
    path('comments/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
    
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'
         ),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'
         ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/templates/includes/footer.html
{% load static %}
    <p>© 2024 Copyright <span style="color:red">Ya</span>tube</p>

yatube/templates/includes/header.html
{% load static %}

<header>
  <nav class="navbar navbar-expand-lg navbar-light justify-content-between" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand d-flex align-items-center nav-pills" href="{% url 'posts:index' %}" style="text-decoration: none;">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span class="ms-2" style="color:red">Ya</span>tube
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavigation" aria-controls="navbarNavigation" aria-expanded="false" aria-label="Переключатель навигации">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNavigation">
        {% with request.resolver_match.view_name as view_name %}
          <ul class="navbar-nav mb-2 mb-lg-0 nav nav-pills">
            {% if user.is_authenticated %}
              <!-- Пункты меню для авторизованного пользователя -->
              <li class="nav-item "> 
                <a class="nav-link {% if view_name == 'about:author' %}active text-white{% endif %}"
                  href="{% url 'about:author' %}">Об авторе</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if view_name == 'about:tech' %}active text-white{% endif %}"
                  href="{% url 'about:tech' %}">Технологии</a>
              </li>
              <li class="nav-item"> 
                <a class="nav-link {% if view_name  == 'posts:post_create' %}active text-white{% endif %}"
                href="{% url 'posts:post_create' %}">Новая запись</a>
              </li>
              <li class="nav-item"> 
                <a class="nav-link {% if view_name  == 'users:password_change_form' %}active text-white{% endif %}"
                href="{% url 'users:password_change_form' %}">Изменить пароль</a>
              </li>
              <li class="nav-item"> 
                <a class="nav-link {% if view_name  == 'users:logout' %}active text-white{% endif %}"
                href="{% url 'users:logout' %}">Выйти</a>
              </li>
              <li class="nav-item">
                Пользователь: {{ user.username }}
              </li>
            {% else %}
              <!-- Пункты меню для неавторизованного пользователя -->
              <li class="nav-item"> 
                <a class="nav-link {% if view_name  == 'about:author' %}active text-white{% endif %}" 
                href="{% url 'about:author' %}">Об авторе</a>
              </li>
              <li class="nav-item">
                <a class="nav-link {% if view_name  == 'about:tech' %}active text-white{% endif %}"
                href="{% url 'about:tech' %}">Технологии</a>
              </li>
              <li class="nav-item"> 
                <a class="nav-link {% if view_name  == 'users:login' %}active text-white{% endif %}"
                href="{% url 'users:login' %}">Войти</a>
              </li>
              <li class="nav-item"> 
                <a class="nav-link {% if view_name  == 'users:signup' %}active text-white{% endif %}"
                href="{% url 'users:signup' %}">Регистрация</a>
              </li>
            {% endif %}
          {% endwith %}
        </ul>
      </div>
    </div>
  </nav>
</header>

yatube/templates/includes/paginator.html
{% comment %}Отрисовываем навигацию паджинатора только если
    все посты не помещаются на первую страницу{% endcomment %}
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
    <ul class="pagination">
    {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
        <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
            Предыдущая
        </a>
        </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
            <li class="page-item active">
            <span class="page-link">{{ i }}</span>
            </li>
        {% else %}
            <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
            </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
            Следующая
        </a>
        </li>
        <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
            Последняя
        </a>
        </li>
    {% endif %}    
    </ul>
</nav>
{% endif %} 