yatube/about/urls.py
from django.urls import path
from . import views


app_name = "about"


urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name='author'),
    path("tech/", views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"


urlpatterns = [
    #Главная страница
    path("", views.index, name='index'),
    # в качестве параметра ожидает slug строку
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),
    path('comments/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
    
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow,
         name='profile_follow'
         ),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'
         ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from core.models import CreatedModel

# Create your models here.
User = get_user_model()


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
        )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts'
        )
    group = models.ForeignKey("Group",
                              on_delete=models.SET_NULL,
                              related_name='posts',
                              blank=True,
                              null=True,
                              verbose_name='Группа',
                              help_text='Выберите группу'
                              )
    # Поле для картинки (необязательное)
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )
    # Аргумент upload_to указывает директорию, 
    # в которую будут загружаться пользовательские файлы
    
    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self) -> str:
        return self.text[:15]


class Group(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, blank=True, max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.title


class Comment(CreatedModel):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        verbose_name="Комментарии к посту",
        related_name="comments",
        blank=True,
        null=True
    )
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='comments',
                               blank=True,
                               null=True
                               )
    text = models.TextField('Текст',
                            help_text='Текст нового комментария'
                            )
    
    def __str__(self):
        return f"{self.author.username} - {self.text}"


class Follow(CreatedModel):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name='follower',
                             verbose_name='Подписчик',
                             blank=True,
                             null=True
                             )
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='following',
                               verbose_name='Автор',
                               blank=True,
                               null=True)

    class Meta:
        unique_together = ['user', 'author']

    def __str__(self):
        return f"{self.user} подписан на {self.author}"

yatube/posts/forms.py
from django import forms
from .models import Post, Comment
from pytils.translit import slugify
from django.core.exceptions import ValidationError


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['text', 'group', 'image']
    
    # Валидация поля slug
    def clean_slug(self):
        """Обрабатывает случай, если slug не уникален."""
        cleaned_data = super().clean()
        slug = cleaned_data.get('slug')
        if not slug:
            title = cleaned_data.get('title')
            slug = slugify(title)[:50]
        if Post.objects.filter(slug=slug).exists():
            raise ValidationError(
                f'Адрес "{slug}" уже существует, '
                'придумайте уникальное значение'
            )
        return slug


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['text']

yatube/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Group, Comment, Follow
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.views.decorators.cache import cache_page

from .forms import PostForm, CommentForm


User = get_user_model()

@cache_page(20, key_prefix='index_page')
def index(request):
    posts_list = Post.objects.all().order_by("-pub_date")
    # Если порядок сортировки определен в классе Meta модели,
    # запрос будет выглядить так:
    # post_list = Post.objects.all()
    # Показывать по 10 записей на странице.
    paginator = Paginator(posts_list, 10)

    # Из URL извлекаем номер запрошенной страницы - это значение параметра page
    page_number = request.GET.get("page")

    # Получаем набор записей для страницы с запрошенным номером
    page_obj = paginator.get_page(page_number)

    context = {
        "page_obj": page_obj
    }
    return render(request, "posts/index.html", context)


def group_posts(request, slug):
    # Получаем объект группы по переданному slug или возвращаем ошибку 404, если группа не найдена
    group = get_object_or_404(Group, slug=slug)
    group_posts = Post.objects.filter(group=group).order_by("-pub_date")
    
    paginator = Paginator(group_posts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        "group": group,
        "group_posts": group_posts,
        "page_obj": page_obj
        }
    return render(request, "posts/group_list.html", context)


@login_required
def profile(request, username):
    """персональная страница автора"""
    author = get_object_or_404(User, username=username)
    user_posts = Post.objects.filter(author=author).order_by("-pub_date")
    paginator = Paginator(user_posts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    following = Follow.objects.filter(user=request.user, author=author)
    
    is_own_profile = request.user == author

    context = {
        "author": author,
        "page_obj": page_obj,
        "following": following,
        "is_own_profile": is_own_profile
    }

    return render(request, "posts/profile.html", context)


@login_required
def post_detail(request, post_id):
    """страница отдельного поста"""
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comments.all()
    form = CommentForm()

    context = {"post": post, "form": form, "comments": comments}
    return render(request, "posts/post_detail.html", context)


@login_required
def post_create(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect("posts:index")
    else:
        form = PostForm()
    return render(request, "posts/create_post.html", {"form": form})

@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.user != post.author:
        return redirect("posts:post_detail", post_id=post_id)

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect("posts:post_detail", post_id=post_id)
    else:
        form = PostForm(instance=post)

    context = {
        "form": form,
        "is_edit": True,
        "post": post,
    }

    return render(request, "posts/create_post.html", context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    form = CommentForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
        return redirect('posts:post_detail', post_id=post_id)

    comments = post.comments.all()
    return render(request, 'posts/post_detail.html', {'post': post, 'form': form, 'comments': comments})


@login_required
def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)

    # Проверяем, имеет ли текущий пользователь право удалять комментарий
    if request.user == comment.author:
        comment.delete()

    # После удаления комментария перенаправляем пользователя на страницу, откуда он пришел
    return redirect(request.META.get('HTTP_REFERER'))


@login_required
def follow_index(request):
    """Посты авторов, на которых подписан текущий пользователь"""
    # Получаем подписки текущего пользователя
    following = Follow.objects.filter(user=request.user)
    # Получаем посты от авторов, на которых подписан текущий пользователь
    posts = Post.objects.filter(
        author__in=[follow.author for follow in following]
        )
    paginator = Paginator(posts, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    context = {
        "following": following,
        "posts": posts,
        "page_obj": page_obj}
    
    return render(request, 'posts/follow.html', context)

@login_required
def profile_follow(request, username):
    """Подписаться на автора"""
    # Получаем пользователя, на которого хочет подписаться текущий пользователь
    author = get_object_or_404(User, username=username)
    # Проверяем, не пытается ли текущий пользователь подписаться на самого себя
    if request.user == author:
        return redirect('posts:profile', username=username)
    # Проверяем, не подписан ли уже текущий пользователь на этого автора
    if Follow.objects.filter(user=request.user, author=author).exists():
        return redirect('posts:profile', username=username)
    # Создаем запись о подписке
    Follow.objects.create(user=request.user, author=author)
    return redirect("posts:profile", username=username)

@login_required
def profile_unfollow(request, username):
    """Отписаться от автора"""
    # Получаем пользователя, от которого хочет отписаться текущий пользователь
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect("posts:profile", username=username)
    # return redirect(request.META.get("HTTP_REFERER"))

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% load static %}


{% block title %}Новый пост{% endblock %}

{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% load user_filters %} 
          {% if is_edit %}
            Редактировать пост
          {% else %}
            Новый пост
          {% endif %}
        </div>
        <div class="card-body">        
          <form method="post" enctype="multipart/form-data" action="{% if is_edit %}{% url 'posts:post_edit' post.id %}{% else %}{% url 'posts:post_create' %}{% endif %}">

            {% csrf_token %}

            <div class="form-group row my-3 p-3">
              <label for="id_text">
                Текст поста                  
                <span class="required text-danger" >*</span>                  
              </label>
              {{ form.text|addclass:"form-control" }}              
              <small id="id_text-help" class="form-text text-muted">
                  Текст нового поста
              </small>                  
            </div>            
            <div class="form-group row my-3 p-3">
              <label for="id_group" class="col-sm-2 col-form-label">Группа</label>
                {{ form.group|addclass:"form-select form-control" }}  
                  <small id="id_group-help" class="form-text text-muted">Группа, к которой будет относиться пост</small>
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_image" class="col-sm-2 col-form-label">Картинка</label>
              {{ form.image|addclass:"form-control" }}  
              <small id="id_image-help" class="form-text text-muted">Изображение для поста</small>
            </div>
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}Посты избранных авторов{% endblock %}

{% block content %}
<div class="container">
  {% include 'posts/includes/switcher.html' %}
  <div class="container">
    <h1>Посты подписанных авторов</h1>
    <div class="row">
        {% for post in page_obj %}
        <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
            {% if post.image %}
            <img src="{{ post.image.url }}" class="card-img-top" alt="{{ post.text }}">
                {% comment %} {% thumbnail post.image "960x339" upscale=True as im %}
                    <img class="card-img my-2" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                {% endthumbnail %} {% endcomment %}
            {% endif %}
            <div class="card-body">
            <p class="card-text">{{ post.text }}</p>
            <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">Автор: {{ post.author.username }}</small>
                <small class="text-muted">Дата публикации: {{ post.pub_date }}</small>
            </div>
            </div>
        </div>
        </div>
        {% if not forloop.last %}<hr>{% endif %}
        {% empty %}
        <p>Нет постов для отображения.</p>
        {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/group_list.html
{%extends "base.html"%}
{% load thumbnail %}

{% block title %}
  {{ group.title }}
{% endblock %}

{% block content %}
  <div class="container py-5">
    <h1> Записи сообщества: {{ group.title }} </h1>
    <p> {{ group.description }} </p>
    <!-- Перебор всех постов в группе -->
    {% if group_posts %}
      <!-- Если есть посты в группе -->
      {% for post in page_obj %}
        <article>
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
              <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
            </li>
            <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
          </ul>
          {% thumbnail post.image "960x339" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
          {%endthumbnail%}
          <p>{{post.text}} </p>
          <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
        </article>
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    {% else %}
      <!-- Если в группе нет постов -->
      <p>В этой группе пока нет постов.</p>
    {% endif %}
    {% include 'posts/includes/paginator.html' %}
  </div>
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% load l10n %}
{% load thumbnail %}
{% load cache %}

{% block title %}
  Последние обновления на сайте
{% endblock %}


{% block content %}
{% comment %} {% cache 20 index_page %} {% endcomment %}
  <div class="container">
    {% include 'posts/includes/switcher.html' %}
      {% for post in page_obj %}
        <article>
          <ul>
            <li>Автор: {{ post.author.get_full_name }}
              <a href="{% url 'posts:profile' username=post.author.username %}">
                все посты пользователя
              </a>
            </li>
            <li>Дата публикации: {{ post.pub_date|date:"d E Y"}}</li>
          </ul>
          {% thumbnail post.image "960x339" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
          {% endthumbnail %}
          <p>{{ post.text }}</p>
          {% if post.group %}
            <a href="{% url 'posts:post_detail' post_id=post.id %}">подробная запись</a><br>
            <a href="{% url 'posts:group_posts' slug=post.group.slug %}">все записи группы</a>
          {% else %}
            <a href="{% url 'posts:group_posts' slug='non-existent-slug' %}">все записи группы</a>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %}
        </article>
      {% endfor %}

      {% include 'posts/includes/paginator.html' %}
    {% comment %} {% endcache %} {% endcomment %}
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}

{% block title %}
    Пост {{ post.text|truncatechars:30 }}
{% endblock %}

{% block content %}
    <div class="container py-5">
        <div class="row">
            {% load user_filters %}
            <aside class="col-12 col-md-3">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        Дата публикации: {{ post.pub_date }}
                    </li>
                    {% if post.group %}
                    <li class="list-group-item">
                        {% if post.group %}
                        Группа: {{ post.group.title }}
                        <a href="{% url 'posts:group_posts' slug=post.group.slug %}">
                            все записи группы
                        </a>
                        {% endif %}
                    </li>
                    {% endif %}
                    <li class="list-group-item">
                        Автор: {{ post.author.username }}
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Всего постов автора: {{ post.author.posts.count }}
                    </li>
                    <li class="list-group-item">
                        <a href="{% url 'posts:profile' username=post.author.username %}">
                            все посты пользователя
                        </a>
                    </li>
                </ul>
            </aside>
            <article class="col-12 col-md-9">
                {% thumbnail post.image "960x339" upscale=True as im %}
                    <img class="card-img my-2" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                {% endthumbnail %}
                <p>
                    {{ post.text }}
                </p>

                {% if request.user == post.author %}
                    <a class="btn btn-primary no-underline" href="{% url 'posts:post_edit' post.pk %}">редактировать запись</a>
                {% endif %}
                
                {% if user.is_authenticated %}
                <div class="card my-4">
                    <h5 class="card-header">Добавить комментарий:</h5>
                    <div class="card-body">
                    <form method="post" action="{% url 'posts:add_comment' post.id %}">
                        {% csrf_token %}      
                        <div class="form-group mb-2">
                        {{ form.text|addclass:"form-control" }}
                        </div>
                        <button type="submit" class="btn btn-primary">Отправить</button>
                    </form>
                    </div>
                </div>
                {% endif %}

                {% for comment in comments %}
                <div class="media mb-4">
                    <div class="media-body">
                    <h5 class="mt-0">
                        <a href="{% url 'posts:profile' comment.author.username %}">
                        {{ comment.author.username }}
                        </a>
                    </h5>
                        <p>
                        {{ comment.text }}
                        </p>
                        {% if user.is_authenticated and user == comment.author %}
                            <form action="{% url 'posts:delete_comment' comment.id %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">Удалить</button>
                            </form>
                        {% endif %} 
                    </div>
                </div>
                {% endfor %}
            </article>
        </div>
    </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}
{% block title %}
    {{ author.get_full_name }} Профайл пользователя
{% endblock %}

{% block content %}
<div class="container py-5">
    <div class="mb-5">
        <h1>Все посты пользователя {{ author.get_full_name }}</h1>
        <h3>Всего постов: {{ posts_count }}</h3>
        {% if not is_own_profile %}
            {% if following %}
            <a class="btn btn-lg btn-light"
                href="{% url 'posts:profile_unfollow' author.username %}" role="button">
                Отписаться
            </a>
            {% else %}
                <a class="btn btn-lg btn-primary"
                href="{% url 'posts:profile_follow' author.username %}" role="button">
                Подписаться
                </a>
            {% endif %}
        {% endif %}
    </div>

    {% for post in page_obj %}
        <article>
            <ul>
                <li>Дата публикации: {{ post.pub_date }}</li>
            </ul>
            {% thumbnail post.image "960x339" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
            {% endthumbnail %}
            <p>{{ post.text }}</p>

            <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a><br>
            {% if post.group %}
                <a href="{% url 'posts:group_posts' slug=post.group.slug %}">все записи группы</a><br>
            {% endif %}

            {% if request.author == post.author %}
                <a href="{% url 'posts:post_edit' post.pk %}">редактировать</a>
            {% endif %}
            {% if not forloop.last %}<hr>{% endif %}
        </article>
    {% endfor %}

    <div class="pagination">
        {% include 'posts/includes/paginator.html' %}
    </div>
</div>
{% endblock %}