yatube/about/urls.py
from django.urls import path
from . import views


app_name = "about"


urlpatterns = [
    path("author/", views.AboutAuthorView.as_view(), name='author'),
    path("tech/", views.AboutTechView.as_view(), name='tech'),
]

yatube/users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    # Полный адрес страницы регистрации - auth/signup/,
    # но префикс auth/ обрабатывется в головном urls.py
    path("signup/", views.SignUp.as_view(), name="signup"),
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path(
        "logout/",
        LogoutView.as_view(template_name="users/logged_out.html"),
        name="logout",
    ),
    path(
        "password_reset/",
        PasswordResetView.as_view(template_name="users/password_reset_form.html"),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path(
        "password_change_form/",
        PasswordChangeView.as_view(template_name="users/password_change_form.html"),
        name="password_change_form",
    ),
    path(
        "password_change/done/",
        PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
        name="password_change_done",
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


#  создадим собственный класс для формы регистрации
#  сделаем его наследником предустановленного класса UserCreationForm
class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        # укажем модель, с которой связана создаваемая форма
        model = User
        # укажем, какие поля должны быть видны в форме и в каком порядке
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/users/views.py
# Импортирую CreateView, чтобы создать ему наследника
from django.views.generic import CreateView
# Функция reverse_lazy позволяет получить URL по параметрам функции path()
from django.urls import reverse_lazy
from .forms import CreationForm


# Create your views here.
class SignUp(CreateView):
    # из какого класса взять форму
    # C какой формой будет работать этот view-класс
    form_class = CreationForm
    # После успешной регистрации перенаправляю пользователя на главную.
    success_url = reverse_lazy('posts:index')
    # Какой шаблон применить для отображения веб-формы
    template_name = 'users/signup.html'

yatube/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Выход
          </div>
          <div class="card-body">
            <p>
              Вы вышли из своей учётной записи. Ждём вас снова!
            </p>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  </div>
</div>
{% endblock %} 

yatube/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{%block content%}
{% load user_filters %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">
                Войти на сайт
            </div>
            <div class="card-body">
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">
                                {{error|escape}}
                            </div>
                        {%endfor%}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            {{error|escape}}
                        </div>
                    {% endfor %}
                {% endif %}

                <form method="post"
                {% if action_url %}
                    action="{% url action_url %}"
                {% endif %}
            >
                {% csrf_token %}
            
                {% for field in form %}
                    <div class="form-group row my-3"
                        {% if field.field.required %} 
                            aria-required="true"
                        {% else %}
                            aria-required="false"
                        {% endif %}
                    >
                        <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">
                            {{ field.label }}
                            {% if field.field.required %}
                                <span class="required text-danger">*</span>
                            {% endif %}
                        </label> 
                        <div class="col-md-6">
                            {{ field|addclass:'form-control' }}
                            {% if field.help_text %}
                                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                                    {{ field.help_text|safe }}
                                </small>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}


                    <div class="form-group row my-3">
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                Войти
                            </button>
                            <a href="{% url 'users:password_reset' %}" class="btn btn-link">
                                Забыли пароль?
                            </a>
                        </div>
                    </div>
                </form>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
</div>

{% endblock %} 

yatube/templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %}Пароль изменён{% endblock %}
{% block content %}
{% load user_filters %}
<div class="container py-5">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Пароль изменён
          </div>
          <div class="card-body"> 
            <p>Пароль изменён успешно</p>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  </div>
</div>
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}Изменение пароля{% endblock %}
{% block content %}
{% load user_filters %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          Изменить пароль
        </div>
        <div class="card-body">
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}

          <form method="post" action="{% url 'users:password_change_form' %}">
            {% csrf_token %}
            
            {% for field in form %}
              <div class="form-group">
                  <label for="{{ field.id_for_label }}">
                      {{ field.label }}
                      {% if field.field.required %}
                          <span class="required text-danger">*</span>
                      {% endif %}
                  </label>  
                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                      <small id="{{ field.id_for_label }}--help" class="form-text text-muted">
                          {{ field.help_text|safe }}
                      </small>
                  {% endif %}
              </div>
            {% endfor %}
            <div class="text-center">
              <button type="submit" class="btn btn-primary">
                Изменить пароль
              </button>
            </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
</div>
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Восстановление пароля завершено
          </div>
          <div class="card-body">
            <p>Ваш пароль был сохранен. Используйте его для входа</p>
            <a href="{% url 'users:login' %}" class="btn btn-primary">Войти</a>
          </div> 
        </div> 
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Новый пароль{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Введите новый пароль
          </div>
          <div class="card-body">
            {% if validlink %}
              {% if validlink %}
              <form method="post">
                {% csrf_token %}
                <div class="form-group">
                  <label for="id_new_password1">Новый пароль:</label>
                  <input type="password" name="new_password1" id="id_new_password1" class="form-control">
                </div>
                <div class="form-group">
                  <label for="id_new_password2">Подтверждение нового пароля:</label>
                  <input type="password" name="new_password2" id="id_new_password2" class="form-control">
                </div>
                <button type="submit" class="btn btn-primary">Сохранить новый пароль</button>
              </form>
              {% endif %}
            {% else %}
            <div class="alert alert-danger">
              <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
            </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block title %}Сброс пароля прошёл успешно{% endblock %}
{% block content %}
{% load user_filters %}
<div class="container py-5">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Отправлено письмо
          </div>
          <div class="card-body"> 
            <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  </div>
</div>
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}Сброс пароля{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
          </div>
          <div class="card-body">
            {% load user_filters %}
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endif %}
            <form method="post" action="{% url 'users:password_reset' %}">
              {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <label for="id_email">
                  Адрес электронной почты
                  <span class="required text-danger">*</span>
                </label>
                <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
              </div>
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Сбросить пароль
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
        <div class="card-body">
          {% load user_filters %} {# Загружаем фильтры #}
          {# Этот блок будет показан, если в форме есть ошибки #}
          {% if form.errors %}
          {% for field in form %}
          {% for error in field.errors %}
          <div class="alert alert-danger">
            {{ error|escape }}
          </div>
          {% endfor %}
          {% endfor %}
          {% for error in form.non_field_errors %}
          <div class="alert alert-danger">
            {{ error|escape }}
          </div>
          {% endfor %}
          {% endif %}

          <form method="post" action="{% url 'users:signup' %}">
            {% csrf_token %}

            {# Вывожу поля в цикле, по отдельности #}
            {% for field in form %}
            <div class="form-group row my-3 p-3">
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                {% if field.field.required %}
                <span class="required text-danger">*</span>
                {% endif %}
              </label>
              {# К полю ввода добавляем атрибут class #}
              {{ field|addclass:'form-control' }}
              {% if field.help_text %}
              <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                {{ field.help_text|safe }}
              </small>
              {% endif %}
            </div>
            {% endfor %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Зарегистрироваться
              </button>
            </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
</div>
{% endblock %}